df <- read.csv("household_power_consumption.txt", sep = ";", na.strings = "?", header = TRUE, stringsAsFactors = FALSE)
df <- subset(df, Date %in% c("1/2/2007","2/2/2007"))
df$Date <- as.Date(df$Date, format = "%d/%m/%Y")
datetime <- paste(as.Date(data1$Date), data1$Time)
df$datetime <- as.POSIXct(datetime)
with(df, { plot(Sub_metering_1~datetime, type="l", ylab="Global Active Power (kilowatts)", xlab="")
       lines(Sub_metering_2~datetime,col='Red')
       lines(Sub_metering_3~datetime,col='Blue')
})
legend("topright", col=c("black", "red", "blue"), lty=1, lwd=2, legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.copy(png, file="plot3.png", height=480, width=480)

dev.off()